VIA = ["Via", "Piazza", "Viale", "Corso", "Strada", "Lungomare", "Piazzale", "Largo", "Vicolo", "Contrada"
       , "Calle", "Salita", "Rampa", "Ponte", "Galleria", "Borgo"]

CITTA = [("AO","AO","Aosta"),
 ("AO","DO","Donnas"),
 ("TO","TO","Torino"),
 ("TO","FR","Front"),
 ("AT","AT","Asti"),
 ("AT","CO","Corsione"),
 ("CN","CN","Cuneo"),
 ("CN","CA","Carrù"),
 ("MI","MI","Milano"),
 ("MI","RH","Rho"),
 ("CO","CO","Como"),
 ("CO","ST","Stazzona"),
 ("MN","MN","Mantova"),
 ("MN","CG","Castel Goffredo"),
 ("CR","CR","Cremona"),
 ("CR","SB","San Bassano"),
 ("BZ","BZ","Bolzano"),
 ("BZ","CH","Chiusa"),
 ("TN","TN","Trento"),
 ("TN","AL","Ala"),
 ("VE","VE","Venezia"),
 ("VE","JE","Jesolo"),
 ("PD","PD","Padova"),
 ("PD","PS","Piove di Sacco"),
 ("VR","VR","Verona"),
 ("VR","ER","Erbe"),
 ("GO","GO","Gorizia"),
 ("GO","MO","Mossa"),
 ("UD","UD","Udine"),
 ("UD","TR","Tricesino"),
 ("TS","TS","Trieste"),
 ("TS","MU","Muggia"),
 ("GE","GE","Genova"),
 ("GE","ZO","Zoagli"),
 ("SP","SP","La Spezia"),
 ("SP","BE","Beverino"),
 ("SV","SV","Savona"),
 ("SV","SS","Borghetto Santo Spirito"),
 ("BO","BO","Bologna"),
 ("BO","IM","Imola"),
 ("FC","FO","Forlì"),
 ("FC","CE","Cesena"),
 ("RA","RA","Ravenna"),
 ("RA","CB","Castel Bolognese"),
 ("AR","AR","Arezzo"),
 ("AR","PO","Poppi"),
 ("PI","PI","Pisa"),
 ("PI","GT","San Giuliano Terme"),
 ("FI","FI","Firenze"),
 ("FI","FR","Firenzuola"),
 ("PU","PE","Pesaro"),
 ("PU","UD","Udine"),
 ("AP","AP","Ascoli Piceno"),
 ("AP","CA","Carassai"),
 ("AN","AN","Ancona"),
 ("AN","FO","Force"),
 ("RM","RM","Roma"),
 ("RM","MO","Montegallo"),
 ("FR","FR","Frosinone"),
 ("FR","CM","Cupra Marittima"),
 ("RI","RI","Rieti"),
 ("RI","BS","Belmonte in Sabina"),
 ("AQ","AQ","L’Aquila"),
 ("AQ","SC","Scoppito"),
 ("CH","CH","Chieti"),
 ("CH","AR","Archi"),
 ("PG","PG","Perugia"),
 ("PG","FO","Force"),
 ("TR","TR","Terni"),
 ("TR","BA","Baschi"),
 ("NA","NA","Napoli"),
 ("NA","MS","Massa di Somma"),
 ("BN","BN","Benevento"),
 ("BN","MA","Montefiore dell'Aso"),
 ("SA","SA","Salerno"),
 ("SA","CO","Corbara"),
 ("CB","CB","Campobasso"),
 ("CB","TO","Toro"),
 ("BA","BA","Bari"),
 ("BA","TU","Turi"),
 ("BT","BA","Barletta"),
 ("BT","AN","Andria"),
 ("MT","MT","Matera"),
 ("MT","SJ","Scanzano Jonico"),
 ("PZ","PZ","Potenza"),
 ("PZ","CA","Carbone"),
 ("RC","RC","Reggio Calabria"),
 ("RC","PL","Plati"),
 ("KR","KR","Crotone"),
 ("KR","VE","Verzino"),
 ("PA","PA","Palermo"),
 ("PA","GR","Gratteri"),
 ("CT","CT","Catania"),
 ("CT","MI","Milo"),
 ("TP","TP","Trapani"),
 ("TP","SN","Santa Ninfa"),
 ("CA","CA","Cagliari"),
 ("CA","CP","Capoterra"),
 ("SS","SS","Sassari"),
 ("SS","MO","Mores")]

NOMI = [
    "Roma", "Garibaldi", "Cavour", "Vittorio Emanuele",
    "Dante Alighieri", "Alessandro Manzoni", "Giuseppe Verdi",
    "Guglielmo Marconi", "Giuseppe Mazzini", "Ugo Foscolo",
    "Giacomo Leopardi", "Francesco Petrarca", "Giosuè Carducci",
    "Cesare Battisti", "Camillo Benso di Cavour",

    "Leonardo da Vinci", "Michelangelo Buonarroti",
    "Raffaello Sanzio", "Galileo Galilei", "Cristoforo Colombo",
    "Amerigo Vespucci", "Marco Polo", "Enrico Fermi",
    "Antonio Meucci",

    "del Popolo", "della Repubblica", "della Libertà",
    "della Pace", "della Vittoria", "dei Mille",
    "dei Caduti", "dei Martiri", "della Resistenza",

    "San Marco", "San Giovanni", "San Francesco",
    "Sant'Antonio", "Santa Lucia", "Santa Maria",
    "San Giuseppe", "San Michele",

    "Duomo", "Castello", "Municipio", "Stazione",
    "Ferrovia", "Mercato", "Porto", "Teatro",
    "Ospedale", "Università",

    "Europa", "Italia", "Trieste", "Venezia",
    "Milano", "Torino", "Napoli", "Palermo",

    "delle Rose", "dei Pini", "delle Vigne",
    "del Sole", "del Mare", "del Ponte",
    "del Mulino", "della Torre", "della Chiesa",

    "degli Artigiani", "delle Industrie",
    "delle Scuole", "degli Alpini",

    "Antico", "Nuovo", "Vecchio", "Moderno",
    "Alto", "Basso", "Centrale"
]

import random

def indirizzo():
    via = random.choice(VIA)
    numero_civico = random.randint(1, 150)
    provincia, sigla, citta = random.choice(CITTA)
    nome = random.choice(NOMI)
    print(f'insert into Indirizzo values ("{provincia}","{sigla}", "{numero_civico}", "{via}", "{nome}");')

for _ in range(15):
    indirizzo()